# Generated by Django 4.0 on 2021-12-17 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_latitude', models.FloatField(blank=True)),
                ('user_longitude', models.FloatField(blank=True)),
                ('user_answer', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trivia_Questions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trivia_questions', models.TextField(blank=True, null=True)),
                ('correct_answer', models.TextField()),
                ('correct_longitude', models.FloatField(blank=True)),
                ('correct_latitude', models.FloatField(blank=True)),
                ('user_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='answers.answers')),
            ],
        ),
    ]
