# Generated by Django 4.0 on 2021-12-21 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('answers', '0002_alter_answers_user_latitude_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trivia_questions',
            name='user_answer',
        ),
    ]
